name: Building and pushing pagamentos-microservice-k8s image to Docker Hub
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  building:
    name: Building pagamentos-microservice-k8s image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push images tags
        uses: docker/build-push-action@v5
        with:
          context: ./pagamentos
          platforms: linux/amd64
          push: true
          tags: |
            perazzojoao/pagamentos-microservice-k8s:latest
            perazzojoao/pagamentos-microservice-k8s:${{ github.ref_name }}
